### ISSUE TITLE
jump 0 is unsound

### ISSUE THREAD

**Issue by andrewthad** [goolord/url-bytes#2]
From the source:

    if colonFirst
      then do
        P.char2 InvalidAuthority '/' '/'
        pure $ fromIntegral $! i1 - 1
      else do
        PU.jump 0
        pure 0

But `jump 0` is never safe. This only works if the offset into the byte sequence being parsed is zero. Otherwise it leads to undefined behavior. I will address this in https://github.com/goolord/url-bytes/pull/1.

**Comment by goolord** [comment]
all of my uses of `cursor` are also only correct when the offset is 0, I will fix that after #1 is merged

**Comment by goolord** [comment]
both of these problems are resolved in #1
